---
title: "4. ER injuries"
---

```{r}
#| include: false

knitr::opts_chunk$set(
  message = FALSE,
  fig.width = 8,
  fig.height = 4,
  fig.align = "center",
  dpi = 300
)
```


## Loading libraries

```{r}
library(shiny)
library(tidyverse)
theme_set(theme_light())
```

## Importing data

```{r}
folder_path <- here::here("01-mastering-shiny/04_ER_injuries/neiss/")

injuries <- vroom::vroom(file.path(folder_path, "injuries.tsv.gz"))
products <- vroom::vroom(file.path(folder_path, "products.tsv"))
population <- vroom::vroom(file.path(folder_path, "population.tsv"))
```

## Exploration

```{r}
injuries_toilet <- injuries |> filter(prod_code == 649)
```

- **Where can we experiment accidents related with toilets?**

```{r}
injuries_toilet |>
  count(location, wt = weight, sort = TRUE)
```

- **What body part is affected?**

```{r}
injuries_toilet|>
  count(body_part, wt = weight, sort = TRUE)
```

- **What is the final diagnosis?**

```{r}
injuries_toilet |>
  count(diag, wt = weight, sort = TRUE) |>
  head()
```

- **How many people have suffer from this result by sex and age?**

  - **Totals**
  
```{r}
injuries_toilet |>
  count(age, sex, wt = weight, sort = TRUE) |>
  ggplot(aes(age, n, colour = sex)) +
  geom_line() +
  labs(y = "Estimated number of injuries")
```

  - **Injure rate by 10,000 people**
  
```{r}
injuries_toilet |>
  count(age, sex, wt = weight, sort = TRUE) |>
  left_join(population, by = c("age", "sex")) |>
  mutate(rate = n / population * 1e4) |>
  ggplot(aes(age, rate, colour = sex)) +
  geom_line(na.rm = TRUE) +
  labs(y = "Injuries per 10,000 people")
```

  - **What can we learn from narratives?**

```{r}
set.seed(125)

injuries_toilet |>
  filter(str_length(narrative) < 100) |>
  sample_n(5) |>
  pull(narrative)

set.seed(NULL)
```
